-- 코드를 입력하세요
# SELECT b.AUTHOR_ID, b.AUTHOR_NAME, a.CATEGORY , SUM(a.PRICE * c.SALES) AS 'TOTAL_SALES'
# FROM BOOK AS a
# JOIN AUTHOR AS b ON a.AUTHOR_ID = b.AUTHOR_ID
# JOIN BOOK_SALES AS c ON a.BOOK_ID = c.BOOK_ID
# WHERE YEAR(c.SALES_DATE) = 2022 AND
# MONTH(c.SALES_DATE) = 01

# GROUP BY b.AUTHOR_NAME , a.CATEGORY

# ORDER BY b.AUTHOR_NAME DESC, a.CATEGORY DESC


SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM((SALES * PRICE)) AS TOTAL_SALES
FROM BOOK_SALES S
JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY A.AUTHOR_ID, CATEGORY DESC