SELECT DISTINCT(CP1.CART_ID) AS CART_ID
FROM CART_PRODUCTS AS CP1
INNER JOIN CART_PRODUCTS AS CP2
    ON CP1.CART_ID = CP2.CART_ID
WHERE CP1.NAME LIKE "%Milk%" AND CP2.NAME LIKE "%Yogurt%"
ORDER BY CART_ID ASC