SELECT ED3.ID AS ID
FROM ECOLI_DATA AS ED3
JOIN (
    SELECT ED1.ID AS SECOND_ID, ED2.PARENT_ID AS SEED
    FROM ECOLI_DATA AS ED1
    JOIN ECOLI_DATA AS ED2
        ON ED1.PARENT_ID = ED2.ID
    ) AS ED
ON ED3.PARENT_ID = ED.SECOND_ID
WHERE SEED IS NULL
ORDER BY ID ASC