SELECT USER_ID, NICKNAME
        , CONCAT(CITY," ", STREET_ADDRESS1," ", STREET_ADDRESS2) AS "전체주소"
        , CONCAT(SUBSTR(TLNO,1,3),"-", SUBSTR(TLNO,4,4),"-", SUBSTR(TLNO,8,4)) AS "전화번호"
FROM USED_GOODS_USER AS UGU
LEFT JOIN(SELECT WRITER_ID
            FROM USED_GOODS_BOARD
            GROUP BY WRITER_ID
            HAVING COUNT(*) > 2) AS WGB
    ON UGU.USER_ID = WGB.WRITER_ID
WHERE WGB.WRITER_ID IS NOT NULL
ORDER BY UGU.USER_ID DESC


