SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
# , AI.SEX_UPON_INTAKE, AO.SEX_UPON_OUTCOME
FROM ANIMAL_INS AS AI
LEFT JOIN ANIMAL_OUTS AS AO
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.SEX_UPON_OUTCOME IS NOT NULL
    AND AI.SEX_UPON_INTAKE LIKE "%Intact%"
    AND AO.SEX_UPON_OUTCOME NOT LIKE "%Intact%"
ORDER BY AI.ANIMAL_ID