-- 코드를 입력하세요
# SELECT a.REST_ID , a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS, b.SCORE
# FROM REST_INFO AS a
# JOIN (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS 'SCORE'
#       FROM REST_REVIEW GROUP BY REST_ID) AS b
#       ON a.REST_ID = b.REST_ID
      
# WHERE INSTR(ADDRESS, '서울')

# ORDER BY b.SCORE DESC, a.FAVORITES DESC
SELECT A.REST_ID, B.REST_NAME, B.FOOD_TYPE, B.FAVORITES, B.ADDRESS, ROUND(AVG(A.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW A
JOIN REST_INFO B ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID
HAVING B.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, B.FAVORITES DESC