SELECT  YEAR(OS.SALES_DATE) AS YEAR 
        , MONTH(OS.SALES_DATE) AS MONTH 
        , UI.GENDER AS GENDER
        , COUNT(DISTINCT(UI.USER_ID)) AS USERS
FROM ONLINE_SALE AS OS
INNER JOIN (
    SELECT *
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
    ) AS UI
ON OS.USER_ID = UI.USER_ID
WHERE UI.USER_ID IS NOT NULL
GROUP BY YEAR , MONTH, GENDER
ORDER BY YEAR ASC , MONTH ASC, GENDER ASC