SELECT PLACES.ID, PLACES.NAME, PLACES.HOST_ID
FROM PLACES
JOIN    
    (SELECT HOST_ID
        FROM PLACES
        GROUP BY HOST_ID
            HAVING COUNT(*) > 1 ) AS A
    ON PLACES.HOST_ID = A.HOST_ID

ORDER BY PLACES.ID ASC