SELECT FR.PRODUCT_ID, FR.PRODUCT_NAME, (FR.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FR
LEFT JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE "2022-05%"
    GROUP BY PRODUCT_ID
    ) AS FO
    ON FR.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCT_ID IS NOT NULL
ORDER BY TOTAL_SALES DESC , PRODUCT_ID ASC