SELECT FH.FLAVOR 
    # , (FH.TOTAL_ORDER + JL.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS FH
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
    ) AS JL
ON FH.FLAVOR = JL.FLAVOR
ORDER BY (FH.TOTAL_ORDER + JL.TOTAL_ORDER) DESC
LIMIT 3
