SELECT MM.MEMBER_NAME, RP.REVIEW_TEXT ,DATE_FORMAT(RP.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW AS RP
LEFT JOIN (
    SELECT MP.MEMBER_NAME AS MEMBER_NAME, MI.MEMBER_ID AS MEMBER_ID
    FROM MEMBER_PROFILE AS MP
    LEFT JOIN (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
        ) AS MI
    ON MP.MEMBER_ID = MI.MEMBER_ID
    WHERE MI.MEMBER_ID IS NOT NULL
    ) AS MM
ON RP.MEMBER_ID = MM.MEMBER_ID
WHERE MM.MEMBER_ID IS NOT NULL

ORDER BY REVIEW_DATE ASC

