-- 코드를 입력하세요
SELECT MCDP_CD as '진료과코드' , count(a.MCDP_CD) as '5월예약건수'
FROM (SELECT *
FROM APPOINTMENT
WHERE YEAR(APNT_YMD) = '2022'
and MONTH(APNT_YMD) = '05') AS a
GROUP BY a.MCDP_CD
ORDER BY count(a.MCDP_CD) ASC, a.MCDP_CD ASC
