SELECT CRCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
LEFT JOIN (SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
            GROUP BY CAR_ID
            ORDER BY CAR_ID) AS CRCRH
ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE CRCRH.CAR_ID IS NOT NULL AND CRCC.CAR_TYPE = "세단"
ORDER BY CRCC.CAR_ID DESC