SELECT 
    SUM(SCORE) AS SCORE , hg.EMP_NO, he.EMP_NAME, he.POSITION, he.EMAIL
FROM HR_GRADE AS hg
    JOIN HR_EMPLOYEES AS he 
        ON hg.EMP_NO = he.EMP_NO
GROUP BY hg.YEAR , hg.EMP_NO 
    HAVING hg.YEAR = 2022
ORDER BY SCORE DESC
LIMIT 1