-- 코드를 입력하세요
SELECT b.CATEGORY as 'CATEGORY' , SUM(a.SALES) as 'TOTAL_SALES'
FROM BOOK_SALES as a
JOIN BOOK as b
ON (a.BOOK_ID = b.BOOK_ID)
WHERE YEAR(a.SALES_DATE) = '2022'
AND MONTH(a.SALES_DATE) = '01'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC